language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8b1
install:
  - export XDG_CACHE_HOME=$HOME/.cache/
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
script:
 - pep8 yamlfield
 - pyflakes yamlfield
 - coverage run setup.py test
after_success:
  - coveralls