language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.7
  - DJANGO_VERSION=1.5.4
matrix:
  exclude:
    - python: "2.5"
      env: "DJANGO_VERSION=1.5.4"
    - python: "3.2"
      env: "DJANGO_VERSION=1.4.7"
    - python: "3.2"
      env: "DJANGO_VERSION=1.3.7"
    - python: "3.2"
      env: "DJANGO_VERSION=1.2.7"
    - python: "3.3"
      env: "DJANGO_VERSION=1.4.7"
    - python: "3.3"
      env: "DJANGO_VERSION=1.3.7"
    - python: "3.3"
      env: "DJANGO_VERSION=1.2.7"
# command to install requirements
install: 
 - pip install -r requirements.txt --use-mirrors
 - pip install -q Django==$DJANGO_VERSION --use-mirrors
# command to run tests
script:
 - pep8 yamlfield
 - pyflakes yamlfield
 - python quicktest.py yamlfield
