language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.13
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
matrix:
  exclude:
    - python: "3.2"
      env: "DJANGO_VERSION=1.4.13"
    - python: "3.2"
      env: "DJANGO_VERSION=1.3.7"
    - python: "3.2"
      env: "DJANGO_VERSION=1.2.7"
    - python: "3.3"
      env: "DJANGO_VERSION=1.4.13"
    - python: "3.3"
      env: "DJANGO_VERSION=1.3.7"
    - python: "3.3"
      env: "DJANGO_VERSION=1.2.7"
    - python: "3.4"
      env: "DJANGO_VERSION=1.4.13"
    - python: "3.4"
      env: "DJANGO_VERSION=1.3.7"
    - python: "3.4"
      env: "DJANGO_VERSION=1.2.7"
# command to install requirements
install: 
 - pip install -r requirements.txt
 - pip install -q Django==$DJANGO_VERSION
# command to run tests
script:
 - pep8 yamlfield
 - pyflakes yamlfield
 - coverage run quicktest.py yamlfield
after_success:
  - coveralls
