language: python
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
  - DJANGO_VERSION=1.7.1
install: 
 - pip install pep8 pyflakes coverage python-coveralls
 - pip install -q Django==$DJANGO_VERSION
 - python setup.py install
script:
 - pep8 yamlfield
 - pyflakes yamlfield
 - coverage run setup.py test
after_success:
  - coveralls
