language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
  - DJANGO_VERSION=1.7.1
install: 
 - pip install -r requirements.txt
 - pip install -q Django==$DJANGO_VERSION
# command to run tests
script:
 - pep8 yamlfield
 - pyflakes yamlfield
 - coverage run quicktest.py yamlfield
after_success:
  - coveralls
