language: python
sudo: false
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO_VERSION=1.9.10
  - DJANGO_VERSION=1.10.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
script:
 - make test
after_success:
  - coveralls
